### ISSUE TITLE
Cannot use GITHUB_TOKEN

### ISSUE THREAD

**Issue by ikngtty** [realglobe-Inc/release-next-pr-action#1]
This is something like a note because what we can do is only to wait for GitHub's improvement.

## Expected Behavior
In a workflow file, we can use GITHUB_TOKEN, which is automatically generated by GitHub Actions.

e.g.
```yml
jobs:
  release_next_pr:
    steps:
      - name: Release Next PR
        uses: realglobe-Inc/release-next-pr-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

And then, it is expected that all functions work well.

## Current Behavior
When the GitHub action runs, a below error occurs.

```txt
##[error]GraphqlError: Resource not accessible by integration
##[error]Docker run failed with exit code 1
```

GraphQL is only used to change pull requests' draft status, so it seems that GITHUB_TOKEN does not have any permission to change draft statuses.

## Current Solution
Register a new token as the repository's secret and use it in workflow files.
The token needs `repo` scope at least.

cf. How to register a secret and use it in workflow files: <https://help.github.com/en/articles/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables>

cf. A corresponding commit: 68c3657

It works but users take labor...
I'm waiting for some situation improvement.
